// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCre3JF9mWBdXhch3Zy4ghDuYGQ7Msc9xY',
    appId: '1:1069146745414:web:c1284365f862a6b0e4f847',
    messagingSenderId: '1069146745414',
    projectId: 'viper23-rental',
    authDomain: 'viper23-rental.firebaseapp.com',
    storageBucket: 'viper23-rental.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMQ0LZ-saqBk1LtXVE554MCpzR92gOwcM',
    appId: '1:1069146745414:android:b9a5835fed4e8264e4f847',
    messagingSenderId: '1069146745414',
    projectId: 'viper23-rental',
    storageBucket: 'viper23-rental.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFaTR4zHuJwenrW4R2e42nEe72DZ_4PAA',
    appId: '1:1069146745414:ios:fb06bf7849adc5cce4f847',
    messagingSenderId: '1069146745414',
    projectId: 'viper23-rental',
    storageBucket: 'viper23-rental.firebasestorage.app',
    iosBundleId: 'com.example.rentalCarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFaTR4zHuJwenrW4R2e42nEe72DZ_4PAA',
    appId: '1:1069146745414:ios:fb06bf7849adc5cce4f847',
    messagingSenderId: '1069146745414',
    projectId: 'viper23-rental',
    storageBucket: 'viper23-rental.firebasestorage.app',
    iosBundleId: 'com.example.rentalCarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCre3JF9mWBdXhch3Zy4ghDuYGQ7Msc9xY',
    appId: '1:1069146745414:web:2595b65620982fb1e4f847',
    messagingSenderId: '1069146745414',
    projectId: 'viper23-rental',
    authDomain: 'viper23-rental.firebaseapp.com',
    storageBucket: 'viper23-rental.firebasestorage.app',
  );
}
